sudo: false
language: node_js
node_js:
  - "5"
  - "4.1"
  - "4.0"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
cache:
  directories:
  - node_modules
before_install:
  - npm install --global npm@3
before_script:
  - npm prune
script:
  - npm run travis
